# Generated by Django 4.2.27 on 2025-12-04 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID from main Peerlogic system",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("primary_email", models.EmailField(blank=True, max_length=254)),
                ("primary_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Practice",
                "verbose_name_plural": "Practices",
                "db_table": "voip_practice",
            },
        ),
        migrations.CreateModel(
            name="ProviderConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Provider-specific configuration (domain, territory, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Setup"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Connection Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_connections",
                        to="voip_admin.practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Connection",
                "verbose_name_plural": "Provider Connections",
                "db_table": "voip_provider_connection",
            },
        ),
        migrations.CreateModel(
            name="VoIPProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("netsapiens", "NetSapiens"),
                            ("ringcentral", "RingCentral"),
                            ("8x8", "8x8"),
                            ("vonage", "Vonage"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("supports_users", models.BooleanField(default=True)),
                ("supports_devices", models.BooleanField(default=True)),
                ("supports_call_queues", models.BooleanField(default=False)),
                ("supports_auto_attendant", models.BooleanField(default=False)),
                ("supports_call_recording", models.BooleanField(default=False)),
                ("supports_voicemail", models.BooleanField(default=True)),
                ("supports_sms", models.BooleanField(default=False)),
                (
                    "api_base_url_template",
                    models.URLField(
                        blank=True,
                        help_text="Template URL, e.g., https://{domain}.netsapiens.com/ns-api/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "VoIP Provider",
                "verbose_name_plural": "VoIP Providers",
                "db_table": "voip_provider",
            },
        ),
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("oauth", "OAuth 2.0"),
                            ("api_key", "API Key"),
                            ("basic", "Basic Auth (Username/Password)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "encrypted_data",
                    models.BinaryField(
                        help_text="Encrypted JSON containing credentials"
                    ),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="voip_admin.providerconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Credential",
                "verbose_name_plural": "Provider Credentials",
                "db_table": "voip_provider_credential",
            },
        ),
        migrations.AddField(
            model_name="providerconnection",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="voip_admin.voipprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerconnection",
            unique_together={("practice", "name")},
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("sync", "Sync"),
                            ("api_call", "API Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        help_text="Request duration in milliseconds", null=True
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="voip_admin.providerconnection",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="voip_admin.practice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voip_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "voip_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["practice", "-created_at"],
                        name="voip_audit__practic_4afd69_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="voip_audit__action_2a2c16_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="voip_audit__resourc_34eb77_idx",
                    ),
                ],
            },
        ),
    ]
