# Generated by Django 4.2.27 on 2025-12-04 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("voip_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("device", "Device"),
                            ("call_queue", "Call Queue"),
                            ("number", "Phone Number"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "peerlogic_id",
                    models.CharField(
                        help_text="Stable ID used in Peerlogic API/UI", max_length=100
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        help_text="Provider-specific ID (e.g., NetSapiens user_id)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_mappings",
                        to="voip_admin.providerconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "ID Mapping",
                "verbose_name_plural": "ID Mappings",
                "db_table": "voip_id_mapping",
                "indexes": [
                    models.Index(
                        fields=["connection", "resource_type", "provider_id"],
                        name="voip_id_map_connect_1c9836_idx",
                    ),
                    models.Index(
                        fields=["connection", "resource_type", "peerlogic_id"],
                        name="voip_id_map_connect_ae2248_idx",
                    ),
                ],
                "unique_together": {("connection", "resource_type", "peerlogic_id")},
            },
        ),
    ]
